osx_image: xcode12.5
language: objective-c

cache: cocoapods
podfile: Podfile

env:
  global:
    - LANG=en_US.UTF-8
    - LC_ALL=en_US.UTF-8
    - XCODE_WORKSPACE=GMObjC.xcworkspace
  matrix:
    - SCHEME="GMObjCDemo"

before_install:
  - env
  - locale
  - gem install cocoapods --no-document --quiet
  - gem install xcpretty --no-document --quiet
  - pod --version
  - pod repo update --silent
  - pod update
  - xcpretty --version
  - xcodebuild -version
  - xcodebuild -showsdks


script:
  - set -o pipefail
  - xcodebuild clean build -workspace "$XCODE_WORKSPACE" -scheme "$SCHEME" -sdk iphonesimulator -configuration Debug | xcpretty -c
  - xcodebuild clean build test -workspace "$XCODE_WORKSPACE" -scheme "$SCHEME" -sdk iphonesimulator -destination "platform=iOS Simulator,name=iPhone 12,OS=latest" -configuration Debug GCC_INSTRUMENT_PROGRAM_FLOW_ARCS=YES GCC_GENERATE_TEST_COVERAGE_FILES=YES | xcpretty -c

after_success:
  - bash <(curl -s https://codecov.io/bash)
